name: "WebRelay"
description: "A Home Assistant addon which emultates the HTTP API of Control by Web Webrelay."
version: "1.0.1"
slug: "webrelay"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
